set t_Co=256
"color twilight256
color desert
syntax on                                                                                                                                                                                                   
set noautoindent
set showmatch
set cursorline
set lazyredraw
set shiftwidth=2
set tabstop=2
